# 0. Import Dependencies

In [25]:
import pandas as pd
import json
import glob
import ipywidgets as widgets
from ipywidgets import interact, Layout
import re
import numpy as np
import random
import os

# 1. Select the population density file you want to merge with demographics files.

In [2]:
#get files
files = []
filepath= r"./data/*"
for pop_file in glob.glob(filepath):
    if ".csv" in pop_file or ".json" in pop_file: 
        files.append(pop_file)

print("Select your population density file:")
pop_file = widgets.Select(options=files, value=files[0], 
                                  description="File: ",
                                  disabled = False,
                                  layout=Layout(width="50%", height="260px"))

def update(file):
    return file

pop_file_select = interact(update, file=pop_file)

Select your population density file:

interactive(children=(Select(description='File: ', layout=Layout(height='260px', width='50%'), options=('./dat…

In [3]:
main = pop_file.value
main_key = ""
ref = {}

for file in files: 
    #get key for dict
    key = re.split(r'\\', file)
    key = key[1].split('.')
    ref[key[0]]= pd.read_json(file)
    if key[0] in main: 
        main_key = key[0]

In [4]:
syn_pop = ref.pop(main_key)
syn_pop

         longitude  latitude  Population  Percent       web_lon       web_lat
727093     19.6629   41.1513           0        0  2.188864e+06  5.034684e+06
727094     19.6629   41.1521           0        0  2.188864e+06  5.034802e+06
727095     19.6629   41.1529           0        0  2.188864e+06  5.034921e+06
727096     19.6629   41.1538           0        0  2.188864e+06  5.035054e+06
727097     19.6629   41.1546           0        0  2.188864e+06  5.035172e+06
...            ...       ...         ...      ...           ...           ...
2200838    20.0629   42.5563           0        0  2.233392e+06  5.244678e+06
2200839    20.0629   42.5571           0        0  2.233392e+06  5.244799e+06
2200840    20.0629   42.5579           0        0  2.233392e+06  5.244920e+06
2200841    20.0629   42.5588           0        0  2.233392e+06  5.245056e+06
2200842    20.0629   42.5596           0        0  2.233392e+06  5.245177e+06

[797148 rows x 6 columns]

# 2. Merge into one dataframe

In [5]:
for key,value in ref.items(): 
        print("Merging "+ key)
        del value["Percent"]
        syn_pop = pd.merge(syn_pop, value, how ="left", on=["latitude", "longitude"])
    
    
    #del syn_pop["Population_density"]

syn_pop

Merging alb_f_0
Merging alb_f_1
Merging alb_f_10
Merging alb_f_15
Merging alb_f_20
Merging alb_f_25
Merging alb_f_30
Merging alb_f_35
Merging alb_f_40
Merging alb_f_45
Merging alb_f_5
Merging alb_f_50
Merging alb_f_55
Merging alb_f_60
Merging alb_f_65
Merging alb_f_70
Merging alb_f_75
Merging alb_f_80
Merging alb_m_0
Merging alb_m_1
Merging alb_m_10
Merging alb_m_15
Merging alb_m_20
Merging alb_m_25
Merging alb_m_30
Merging alb_m_35
Merging alb_m_40
Merging alb_m_45
Merging alb_m_5
Merging alb_m_50
Merging alb_m_55
Merging alb_m_60
Merging alb_m_65
Merging alb_m_70
Merging alb_m_75

,longitude,latitude,Population,Percent,web_lon,web_lat,pop_f_0,pop_f_1,pop_f_10,pop_f_15,...,pop_m_35,pop_m_40,pop_m_45,pop_m_5,pop_m_50,pop_m_55,pop_m_60,pop_m_65,pop_m_70,pop_m_75
0,19.6629,41.1513,0,0,2.188864e+06,5.034684e+06,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,19.6629,41.1521,0,0,2.188864e+06,5.034802e+06,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,19.6629,41.1529,0,0,2.188864e+06,5.034921e+06,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,19.6629,41.1538,0,0,2.188864e+06,5.035054e+06,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,19.6629,41.1546,0,0,2.188864e+06,5.035172e+06,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797143,20.0629,42.5563,0,0,2.233392e+06,5.244678e+06,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
797144,20.0629,42.5571,0,0,2.233392e+06,5.244799e+06,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
797145,20.0629,42.5579,0,0,2.233392e+06,5.244920e+06,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
797146,20.0629,42.5588,0,0,2.233392e+06,5.245056e+06,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
797147,20.0629,42.5596,0,0,2.233392e+06,5.245177e+06,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

# 3. Compare population density to demographic totals

In [11]:
syn_pop = syn_pop.replace(np.nan,0)
syn_pop["dem_total"] = syn_pop[syn_pop.columns[6:]].sum(axis=1)
syn_pop

,longitude,latitude,Population,Percent,web_lon,web_lat,pop_f_0,pop_f_1,pop_f_10,pop_f_15,...,pop_m_40,pop_m_45,pop_m_5,pop_m_50,pop_m_55,pop_m_60,pop_m_65,pop_m_70,pop_m_75,dem_total
0,19.6629,41.1513,0.0,0,2.188864e+06,5.034684e+06,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,19.6629,41.1521,0.0,0,2.188864e+06,5.034802e+06,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
2,19.6629,41.1529,0.0,0,2.188864e+06,5.034921e+06,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
3,19.6629,41.1538,0.0,0,2.188864e+06,5.035054e+06,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
4,19.6629,41.1546,0.0,0,2.188864e+06,5.035172e+06,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
797143,20.0629,42.5563,0.0,0,2.233392e+06,5.244678e+06,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
797144,20.0629,42.5571,0.0,0,2.233392e+06,5.244799e+06,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
797145,20.0629,42.5579,0.0,0,2.233392e+06,5.244920e+06,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
797146,20.0629,42.5588,0.0,0,2.233392e+06,5.245056e+06,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
797147,20.0629,42.5596,0.0,0,2.233392e+06,5.245177e+06,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [12]:
total = syn_pop["Population"].sum()
dem_total = syn_pop["dem_total"].sum()
print ("Your population density total is {}".format(total))
print("Your demographic total is {}".format(total))

def fill_dems(row, diff):
    while diff>0:
        choice = random.choice(list(syn_pop.columns[6:-2]))
        row[choice] += 1
        diff -= 1

if total == dem_total:
    print("Density and Demographic totals are equal no further action required.")
else: 
    if total > dem_total: #changes 
        print("The population total is more thant the demogrpahic total, this will take awhile to compute...")
        #TODO Come up with better way
        syn_pop['fill'] = np.where((syn_pop['dem_total'] < syn_pop['Population']),
                                   syn_pop['Population']-syn_pop["dem_total"], 0) 
        for idx, row in syn_pop.iterrows():
            if row["fill"] >0:
                fill_dems(row, row["fill"])   
    else: 
        print("Your demographic population is more than your population density,\
        your population density now reflects the demographic data.")
        syn_pop["Population"] = syn_pop["dem_total"]
        del syn_pop["dem_total"]

Your population density total is 1607939.0
Your demographic total is 1607939.0
Density and Demographic totals are equal no further action required.

# 4. Save your file

In [49]:
print("Do you want to drop 0 values to make a smaller file?")
drop =["Yes", "No"]
drop_0 = widgets.Dropdown(options=drop,
                          value= drop[0],                        
                          description="Drop: ",
                          disabled = False)

def update1(Drop):
    return Drop


drop_select = interact(update1, Drop= drop_0)

print("Do you want to save as a csv or json?")

file_type = ["csv", "json"]

file_select = widgets.Dropdown(options=file_type,
                               value = file_type[0],
                               description="File",disabled = False)

def update2(File_type):
    return File_type



file_selected = interact(update2, File_type= file_select)

Do you want to drop 0 values to make a smaller file?

interactive(children=(Dropdown(description='Drop: ', options=('Yes', 'No'), value='Yes'), Output()), _dom_clas…

Do you want to save as a csv or json?

interactive(children=(Dropdown(description='File', options=('csv', 'json'), value='csv'), Output()), _dom_clas…

In [50]:
if drop_0.value == "Yes":
    syn_pop = syn_pop[syn_pop["Population"]!=0]

filepath = os.path.join(r".\data", "synthetic_population")
    
if file_select.value == "csv":
    filepath =filepath+".csv"
    syn_pop.to_csv(filepath)
    print(filepath + " is saved.")
else: 
    filepath =filepath+".json"
    syn_pop.to_json(filepath)
    print(filepath + " is saved")

.\data\synthetic_population.csv is saved.